name: Clustering_Agent_Latent_Space
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.9
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.7.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astunparse==1.6.3
      - attrs==24.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - bokeh==3.6.2
      - box2d-py==2.3.5
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorcet==3.1.0
      - colorful==0.5.6
      - contourpy==1.3.1
      - cucim-cu12==24.10.0
      - cuda-python==12.6.2.post1
      - cudf-cu12==24.10.1
      - cugraph-cu12==24.10.0
      - cuml-cu12==24.10.0
      - cuproj-cu12==24.10.0
      - cupy-cuda12x==13.3.0
      - cuspatial-cu12==24.10.0
      - cuvs-cu12==24.10.0
      - cuxfilter-cu12==24.10.0
      - cycler==0.12.1
      - dask==2024.9.0
      - dask-cuda==24.10.0
      - dask-cudf-cu12==24.10.1
      - dask-expr==1.1.14
      - datashader==0.16.3
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distlib==0.3.9
      - distributed==2024.9.0
      - distributed-ucxx-cu12==0.40.0
      - dm-tree==0.1.8
      - etils==1.11.0
      - farama-notifications==0.0.4
      - fastapi==0.115.6
      - fastjsonschema==2.21.1
      - fastrlock==0.8.2
      - ffmpeg==1.4
      - filelock==3.16.1
      - flappy-bird-gymnasium==0.4.0
      - flatbuffers==24.3.25
      - fonttools==4.55.2
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gast==0.6.0
      - geopandas==1.0.1
      - glfw==2.8.0
      - google-api-core==2.23.0
      - google-auth==2.36.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.66.0
      - gputil==1.4.0
      - grpcio==1.68.1
      - gymnasium==1.0.0
      - h11==0.14.0
      - h5py==3.12.1
      - holoviews==1.20.0
      - httptools==0.6.4
      - idna==3.10
      - imageio==2.36.1
      - imageio-ffmpeg==0.5.1
      - imbalanced-learn==0.12.4
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - isoduration==20.11.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-server==2.14.2
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - keras==3.7.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - libcudf-cu12==24.10.1
      - libcuspatial-cu12==24.10.0
      - libucx-cu12==1.17.0.post1
      - libucxx-cu12==0.40.0
      - lightning==2.4.0
      - lightning-utilities==0.11.9
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - locket==1.0.0
      - lz4==4.3.3
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.15.0
      - mistune==3.0.2
      - ml-dtypes==0.4.1
      - moviepy==2.1.1
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mujoco==3.2.6
      - multidict==6.1.0
      - multipledispatch==1.0.0
      - namex==0.0.8
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - networkx==3.4.2
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - nvtx==0.2.10
      - nx-cugraph-cu12==24.10.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - optree==0.13.1
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - panel==1.5.4
      - param==2.1.1
      - partd==1.4.2
      - pillow==10.4.0
      - platformdirs==4.3.6
      - proglog==0.1.10
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - proto-plus==1.25.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - py-spy==0.4.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pyct==0.5.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygame==2.6.1
      - pygments==2.18.0
      - pylibcudf-cu12==24.10.1
      - pylibcugraph-cu12==24.10.0
      - pylibraft-cu12==24.10.0
      - pynvjitlink-cu12==0.4.0
      - pynvml==11.4.1
      - pyogrio==0.10.0
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==2.0.7
      - pytorch-lightning==2.4.0
      - pytz==2024.2
      - pyviz-comms==3.0.3
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - raft-dask-cu12==24.10.0
      - rapids-dask-dependency==24.10.0
      - ray==2.39.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rmm-cu12==24.10.0
      - rpds-py==0.22.3
      - rsa==4.9
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - selenium==4.27.1
      - send2trash==1.8.3
      - shapely==2.0.6
      - simpervisor==1.0.0
      - six==1.17.0
      - smart-open==7.0.5
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - starlette==0.41.3
      - swig==4.3.0
      - sympy==1.13.1
      - tblib==3.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - tetris-gymnasium==0.2.1
      - textual==0.89.1
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.5.1
      - torchmetrics==1.6.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treelite==4.3.0
      - trio==0.27.0
      - trio-websocket==0.11.1
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - uc-micro-py==1.0.3
      - ucx-py-cu12==0.40.0
      - ucxx-cu12==0.40.0
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - uvloop==0.21.0
      - virtualenv==20.28.0
      - watchfiles==1.0.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.1
      - werkzeug==3.1.3
      - wrapt==1.17.0
      - wsproto==1.2.0
      - xarray==2024.11.0
      - xyzservices==2024.9.0
      - yarl==1.18.3
      - zict==3.0.0
      - zipp==3.21.0
variables:
  PYTHONPATH: .
