name: Clustering_Agent_Latent_Space
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - aom=3.9.1
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorful=0.5.6
  - cryptography=43.0.1
  - dav1d=1.2.1
  - distlib=0.3.8
  - dm-tree=0.1.8
  - farama-notifications=0.0.4
  - filelock=3.16.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - google-api-core=2.20.0
  - google-auth=2.35.0
  - googleapis-common-protos=1.65.0
  - grpcio=1.62.2
  - gymnasium=0.28.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.1.1
  - imageio=2.35.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.3
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libnl=3.10.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=15.0.2
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - memray=1.12.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.0
  - packaging=24.1
  - pandas=2.1.4
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - prometheus_client=0.21.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - py-spy=0.3.14
  - pyarrow=15.0.2
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.2
  - pyu2f=0.1.5
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - rav1e=0.6.6
  - ray-core=2.37.0
  - ray-data=2.37.0
  - ray-default=2.37.0
  - ray-rllib=2.37.0
  - ray-train=2.37.0
  - ray-tune=2.37.0
  - rdma-core=53.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.1
  - rpds-py=0.20.0
  - rsa=4.9
  - s2n=1.4.13
  - scikit-image=0.24.0
  - scipy=1.14.1
  - setproctitle=1.3.3
  - setuptools=75.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - smart_open=7.0.4
  - snappy=1.2.1
  - sqlite=3.45.2
  - svt-av1=2.2.1
  - tensorboardx=2.6.2.2
  - textual=0.81.0
  - tifffile=2024.9.20
  - tk=8.6.13
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucx=1.15.0
  - urllib3=2.2.3
  - virtualenv=20.21.0
  - wheel=0.44.0
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.22.0
  - zstd=1.5.5
