name: Clustering_Agent_Latent_Space
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.5
  - aiohttp-cors=0.7.0
  - aiosignal=1.3.1
  - alsa-lib=1.2.12
  - annotated-types=0.7.0
  - aom=3.9.1
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=24.2.0
  - aws-c-auth=0.7.20
  - aws-c-cal=0.6.12
  - aws-c-common=0.9.17
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.8
  - aws-sdk-cpp=1.11.267
  - blas=1.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.33.1
  - c-blosc2=2.14.4
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorful=0.5.6
  - cryptography=43.0.1
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - dav1d=1.2.1
  - dbus=1.13.18
  - distlib=0.3.8
  - dm-tree=0.1.8
  - expat=2.6.3
  - farama-notifications=0.0.4
  - ffmpeg=4.4.0
  - filelock=3.16.1
  - fluidsynth=2.3.6
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.82.1
  - glib-tools=2.82.1
  - glog=0.7.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-api-core=2.20.0
  - google-auth=2.35.0
  - googleapis-common-protos=1.65.0
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gymnasium=0.28.1
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.1.1
  - imageio=2.35.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2022.0.1
  - jack=1.9.22
  - jax-jumpy=1.0.0
  - jinja2=3.1.4
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jxrlib=1.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.7.1
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.82.1
  - libgomp=14.1.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwy=1.1.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - libjxl=0.10.3
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libmad=0.15.1b
  - libnghttp2=1.58.0
  - libnl=3.10.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=15.0.2
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=255
  - libtasn1=4.19.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - memray=1.12.0
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpg123=1.32.6
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numpy=1.26.4
  - opencensus=0.11.3
  - opencensus-context=0.1.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - opusfile=0.12
  - orc=2.0.0
  - packaging=24.1
  - pandas=2.1.4
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.11.0
  - portaudio=19.6.0
  - portmidi=2.0.4
  - prometheus_client=0.21.0
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - py-spy=0.3.14
  - pyarrow=15.0.2
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pygame=2.6.1
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.2
  - pyu2f=0.1.5
  - pywavelets=1.7.0
  - pyyaml=6.0.2
  - rav1e=0.6.6
  - ray-core=2.37.0
  - ray-data=2.37.0
  - ray-default=2.37.0
  - ray-rllib=2.37.0
  - ray-train=2.37.0
  - ray-tune=2.37.0
  - rdma-core=53.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rich=13.9.1
  - rpds-py=0.20.0
  - rsa=4.9
  - s2n=1.4.13
  - scikit-image=0.24.0
  - scipy=1.14.1
  - sdl2=2.30.7
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.22.0
  - setproctitle=1.3.3
  - setuptools=75.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - smart_open=7.0.4
  - snappy=1.2.1
  - sqlite=3.45.2
  - svt-av1=2.2.1
  - sympy=1.13.2
  - tensorboardx=2.6.2.2
  - textual=0.81.0
  - tifffile=2024.9.20
  - tk=8.6.13
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucx=1.15.0
  - urllib3=2.2.3
  - virtualenv=20.21.0
  - wheel=0.44.0
  - wrapt=1.16.0
  - x264=1!161.3030
  - x265=3.5
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.11
  - xorg-xorgproto=2024.1
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zfp=1.0.1
  - zipp=3.20.2
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.22.0
  - zstd=1.5.5
