from configurations.structure.reinforcement_learning_configuration import ReinforcementLearningConfiguration


basic_reinforcement_learning_configuration = ReinforcementLearningConfiguration()
basic_reinforcement_learning_configuration.number_environment_runners = 15
basic_reinforcement_learning_configuration.checkpoint_frequency = 50
basic_reinforcement_learning_configuration.number_checkpoint_to_keep = 1
