from configurations.structure.reinforcement_learning_configuration import ReinforcementLearningConfiguration


local_reinforcement_learning_configuration = ReinforcementLearningConfiguration()
local_reinforcement_learning_configuration.ray_local_mode = True
