from configurations.reinforcement_learning.reinforcement_learning_configuration import ReinforcementLearningConfiguration


minimal_cartpole = ReinforcementLearningConfiguration('CartPole')
minimal_cartpole.environment_configuration = {}
