from configurations.reinforcement_learning.reinforcement_learning_configuration import ReinforcementLearningConfiguration

minimal_lunar_lander = ReinforcementLearningConfiguration('LunarLander')
minimal_lunar_lander.environment_configuration = {}
