from configurations.reinforcement_learning.reinforcement_learning_configuration import ReinforcementLearningConfiguration


minimal_reinforcement_learning_configuration = ReinforcementLearningConfiguration()
