from configurations.reinforcement_learning.basic_reinforcement_learning_configuration import basic_reinforcement_learning_configuration
from configurations.structure.experimentation_configuration import ExperimentationConfiguration


lunar_lander = ExperimentationConfiguration(
    experimentation_name='lunar_lander',
    environment_name='LunarLander',
)
lunar_lander.reinforcement_learning_configuration = basic_reinforcement_learning_configuration
